class Test:
    def __init__(self, ktp_name: str):
        self.ktp_name = ktp_name
        self.test_dict = {
            'abdurrauf': {
                'provinsi': 'PROVINSI SULAWESI SELATAN',
                'kota_atau_kabupaten': 'KABUPATEN SOPPENG',
                'nik': '7312042510720002',
                'nama': 'ABDURRAUF, S.Pd, M.Pd',
                'tempat_lahir': 'CELLENGENGE',
                'tanggal_lahir': '25-10-1972',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'O',
                'alamat': 'JL. MERDEKA NO.43',
                'rt': '001',
                'rw': '004',
                'kelurahan_atau_desa': 'BILA',
                'kecamatan': 'LALABATA',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'PEGAWAI NEGERI SIPIL (PNS)',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'adinata': {
                'provinsi': 'PROVINSI KALIMANTAN BARAT',
                'kota_atau_kabupaten': 'KOTA PONTIANAK',
                'nik': '6171042906910005',
                'nama': 'ADINATA',
                'tempat_lahir': 'PONTIANAK',
                'tanggal_lahir': '29-06-1991',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'JL. SELAT PANJANG',
                'rt': '004',
                'rw': '020',
                'kelurahan_atau_desa': 'SIANTAN HULU',
                'kecamatan': 'PONTIANAK UTARA',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '29-06-2017'
                },
            'amat': {
                'provinsi': 'PROVINSI JAWA TENGAH',
                'kota_atau_kabupaten': 'KABUPATEN PEKALONGAN',
                'nik': '3329091003780012',
                'nama': 'AMAT FAOZI',
                'tempat_lahir': 'PEKALONGAN',
                'tanggal_lahir': '10-03-1978',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'DUSUN KAUMAN',
                'rt': '002',
                'rw': '005',
                'kelurahan_atau_desa': 'KESESI',
                'kecamatan': 'KESESI',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'PEDAGANG',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'ariel': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KOTA BOGOR',
                'nik': '3271022106990002',
                'nama': 'ARIEL TANDIAPA',
                'tempat_lahir': 'BOGOR',
                'tanggal_lahir': '21-06-1999',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'O',
                'alamat': 'PULO ARMIN NO.27',
                'rt': '006',
                'rw': '004',
                'kelurahan_atau_desa': 'BARANANGSIANG',
                'kecamatan': 'BOGOR TIMUR',
                'agama': 'KRISTEN',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'arief': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KOTA CIMAHI',
                'nik': '3217061804870007',
                'nama': 'ARIEF WIJAYA PUTRA',
                'tempat_lahir': 'BANDUNG',
                'tanggal_lahir': '18-04-1987',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'JL. AMIR MAHMUD GG. SIRNAGALIH NO. 62',
                'rt': '005',
                'rw': '006',
                'kelurahan_atau_desa': 'CIBABAT',
                'kecamatan': 'CIMAHI UTARA',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'benny': {
                'provinsi': 'PROVINSI DKI JAKARTA',
                'kota_atau_kabupaten': 'JAKARTA SELATAN',
                'nik': '3174071602530001',
                'nama': 'BENNY DARMAWAN USMAN',
                'tempat_lahir': 'U.PANDANG',
                'tanggal_lahir': '16-02-1953',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'O',
                'alamat': 'JL.ANTENE IV/9',
                'rt': '016',
                'rw': '002',
                'kelurahan_atau_desa': 'GANDARIA UTARA',
                'kecamatan': 'KEBAYORAN BARU',
                'agama': 'KATHOLIK',
                'status_perkawinan': 'CERAI HIDUP',
                'pekerjaan': 'PENSIUNAN',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'billy': {
                'provinsi': 'PROVINSI DKI JAKARTA',
                'kota_atau_kabupaten': 'JAKARTA TIMUR',
                'nik': '3175070101909999',
                'nama': 'BILLY BUMBLEBEE SIFULAN',
                'tempat_lahir': 'SURABAYA',
                'tanggal_lahir': '01-01-1990',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'AB',
                'alamat': 'JL DIMANA NO 100',
                'rt': '001',
                'rw': '001',
                'kelurahan_atau_desa': 'ANTAH BERANTAH',
                'kecamatan': 'DUREN SAWIT',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'KARYAWAN SWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'debby': {
                'provinsi': 'PROVINSI DKI JAKARTA',
                'kota_atau_kabupaten': 'JAKARTA SELATAN',
                'nik': '3174096112900001',
                'nama': 'DEBBY ANGGRAINI',
                'tempat_lahir': 'JAKARTA',
                'tanggal_lahir': '21-12-1990',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': '-',
                'alamat': 'JL KECAPI V',
                'rt': '006',
                'rw': '005',
                'kelurahan_atau_desa': 'JAGAKARSA',
                'kecamatan': 'JAGAKARSA',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'KARYAWAN SWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '21-12-2016'
                },
            'edo': {
                'provinsi': 'PROVINSI SUMATERA UTARA',
                'kota_atau_kabupaten': 'KABUPATEN NIAS',
                'nik': '1204050503670001',
                'nama': 'EDO PURNAMA',
                'tempat_lahir': 'NIAS',
                'tanggal_lahir': '05-03-1967',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'B',
                'alamat': 'DUSUN II HILIHAMBAWA',
                'rt': '001',
                'rw': '003',
                'kelurahan_atau_desa': 'HILIGODU TANOSEO',
                'kecamatan': 'HILIDUHO',
                'agama': 'KATHOLIK',
                'status_perkawinan': 'CERAI HIDUP',
                'pekerjaan': 'WARTAWAN',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '05-03-2018'
                },
            'eriko': {
                'provinsi': 'PROVINSI KALIMANTAN BARAT',
                'kota_atau_kabupaten': 'KABUPATEN MEMPAWAH',
                'nik': '6102180503820001',
                'nama': 'ERIKO',
                'tempat_lahir': 'MEMPAWAH',
                'tanggal_lahir': '05-03-1982',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'B',
                'alamat': 'JL. DJOHANSYAH BAKRI',
                'rt': '016',
                'rw': '005',
                'kelurahan_atau_desa': 'ANTIBAR',
                'kecamatan': 'MEMPAWAH TIMUR',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'KARYAWAN BUMN',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'fatchur': {
                'provinsi': 'PROVINSI JAWA TIMUR',
                'kota_atau_kabupaten': 'KABUPATEN JEMBER',
                'nik': '3509190102670006',
                'nama': 'FATCHUR ROCHMAN',
                'tempat_lahir': 'JEMBER',
                'tanggal_lahir': '01-02-1967',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'GRAHA CITRA MAS BLOK I NO 4.LINGK.GUMUK BAGO',
                'rt': '001',
                'rw': '021',
                'kelurahan_atau_desa': 'TEGALBESAR',
                'kecamatan': 'KALIWATES',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'PEGAWAI NEGERI SIPIL (PNS)',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'febrina':{
                'provinsi': 'PROVINSI DKI JAKARTA',
                'kota_atau_kabupaten': 'JAKARTA TIMUR',
                'nik': '3175076508940009',
                'nama': 'FEBRINA RESHITA DEVI',
                'tempat_lahir': 'JAKARTA',
                'tanggal_lahir': '25-08-1994',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': '-',
                'alamat': 'JL. KELURAHAN IV',
                'rt': '011',
                'rw': '011',
                'kelurahan_atau_desa': 'DUREN SAWIT',
                'kecamatan': 'DUREN SAWIT',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'KARYAWAN SWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'fitrokhah':{
                'provinsi': 'PROVINSI JAWA TENGAH',
                'kota_atau_kabupaten': 'KABUPATEN WONOSOBO',
                'nik': '3307114404920004',
                'nama': 'FITROKHAH KHASANAH',
                'tempat_lahir': 'WONOSOBO',
                'tanggal_lahir': '04-04-1992',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': 'B',
                'alamat': 'KALIBEBER',
                'rt': '003',
                'rw': '001',
                'kelurahan_atau_desa': 'KALIBEBER',
                'kecamatan': 'MOJOTENGAH',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'WIRASWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'frida': {
                'provinsi': 'PROVINSI JAWA TIMUR',
                'kota_atau_kabupaten': 'KABUPATEN MALANG',
                'nik': '3507224209890002',
                'nama': 'FRIDA WAHYU M',
                'tempat_lahir': 'MALANG',
                'tanggal_lahir': '02-09-1989',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': '-',
                'alamat': 'JL TIRTO RAHAYU II/2',
                'rt': '001',
                'rw': '005',
                'kelurahan_atau_desa': 'LANDUNGSARI',
                'kecamatan': 'DAU',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'KARYAWAN BUMN',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '02-09-2017'
                },
            'galang': {
                'provinsi': 'PROVINSI BENGKULU',
                'kota_atau_kabupaten': 'KOTA BENGKULU',
                'nik': '1771042401930002',
                'nama': 'GALANG RAKA PRATAMA',
                'tempat_lahir': 'BENGKULU',
                'tanggal_lahir': '24-01-1993',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'A',
                'alamat': 'JLUNIB PERMA III NO 35 PERUMNAS UNIB',
                'rt': '015',
                'rw': '003',
                'kelurahan_atau_desa': 'PEMATANG GUBERNUR',
                'kecamatan': 'MUARA BANGKAHULU',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '24-01-2017'
                },
            'gilang': {
                'provinsi': 'PROVINSI JAWA TENGAH',
                'kota_atau_kabupaten': 'KABUPATEN BANYUMAS',
                'nik': '3302101602980003',
                'nama': 'GILANG RIZQI ABDULLAH',
                'tempat_lahir': 'BANYUMAS',
                'tanggal_lahir': '16-02-1998',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'PEKAJA',
                'rt': '001',
                'rw': '001',
                'kelurahan_atau_desa': 'PEKAJA',
                'kecamatan': 'KALIBAGOR',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'guohui': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KABUPATEN CIANJUR',
                'nik': '3203012503770011',
                'nama': 'GUOHUI CHEN',
                'tempat_lahir': 'FUJIAN',
                'tanggal_lahir': '25-03-1977',
                'jenis_kelamin': 'MALE',
                'golongan_darah': '-',
                'alamat': 'JL SELAMET PERUMAHAN RANCABALI NO. 40',
                'rt': '002',
                'rw': '004',
                'kelurahan_atau_desa': 'MUKA',
                'kecamatan': 'CIANJUR',
                'agama': 'CHRISTIAN',
                'status_perkawinan': 'MARRIED',
                'pekerjaan': 'OTHERS',
                'kewarganegaraan': 'CHINA',
                'berlaku_hingga': '12-12-2023'
                },
            'handoko': {
                'provinsi': 'PROVINSI KEPULAUAN RIAU',
                'kota_atau_kabupaten': 'KOTA BATAM',
                'nik': '2171101212749021',
                'nama': 'HANDOKO',
                'tempat_lahir': 'BANJARMASIN',
                'tanggal_lahir': '12-12-1974',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'GOLDEN LAND BLOK. F NO. 39',
                'rt': '002',
                'rw': '013',
                'kelurahan_atau_desa': 'TAMAN BALOI',
                'kecamatan': 'BATAM KOTA',
                'agama': 'KRISTEN',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'WIRASWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'haqi': {
                'provinsi': 'PROVINSI JAWA TENGAH',
                'kota_atau_kabupaten': 'KABUPATEN PEMALANG',
                'nik': '3327082609000001',
                'nama': 'HAQI HASAN BUNAYA',
                'tempat_lahir': 'PEMALANG',
                'tanggal_lahir': '26-09-2000',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'JL. MUJAHER',
                'rt': '003',
                'rw': '008',
                'kelurahan_atau_desa': 'WIDURI',
                'kecamatan': 'PEMALANG',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'BELUM/TIDAK BEKERJA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'jelty': {
                'provinsi': 'PROVINSI SULAWESI UTARA',
                'kota_atau_kabupaten': 'KABUPATEN MINAHASA SELATAN',
                'nik': '7105074205820001',
                'nama': 'JELTY JEINE KORDAK',
                'tempat_lahir': 'MOTOLING',
                'tanggal_lahir': '18-05-1982',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': '-',
                'alamat': 'JAGA VI',
                'rt': '-',
                'rw': '-',
                'kelurahan_atau_desa': 'MOTOLING II',
                'kecamatan': 'MOTOLING',
                'agama': 'KRISTEN',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'MENGURUS RUMAH TANGGA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'juliana': {
                'provinsi': 'PROVINSI BANTEN',
                'kota_atau_kabupaten': 'KABUPATEN TANGERANG',
                'nik': '3603284407690007',
                'nama': 'JULIANA',
                'tempat_lahir': 'JAKARTA',
                'tanggal_lahir': '04-07-1969',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': 'O-',
                'alamat': 'GADING SERPONG 7B DD.7 NO. 29',
                'rt': '004',
                'rw': '003',
                'kelurahan_atau_desa': 'CURUG SANGERENG',
                'kecamatan': 'KELAPA DUA',
                'agama': 'KRISTEN',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'WIRASWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '04-07-2018'
                },
            'lilly': {
                'provinsi': 'PROVINSI SULAWESI UTARA',
                'kota_atau_kabupaten': 'KOTA MANADO',
                'nik': '7171076007800001',
                'nama': 'LILLY NENDER',
                'tempat_lahir': 'MANADO',
                'tanggal_lahir': '20-07-1980',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': '-',
                'alamat': 'LINGKUNGAN VI',
                'rt': '000',
                'rw': '000',
                'kelurahan_atau_desa': 'TELING ATAS',
                'kecamatan': 'WANEA',
                'agama': 'KATHOLIK',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'KARYAWAN SWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'luki': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KABUPATEN SUMEDANG',
                'nik': '3211111512900007',
                'nama': 'LUKI SETIAWAN',
                'tempat_lahir': 'SUMEDANG',
                'tanggal_lahir': '15-12-1990',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'O+',
                'alamat': 'DUSUN NARINGUL',
                'rt': '001',
                'rw': '004',
                'kelurahan_atau_desa': 'SAWAHDADAP',
                'kecamatan': 'CIMANGGUNG',
                'agama': 'ISLAM',
                'status_perkawinan': 'Kawin',
                'pekerjaan': 'PERAWAT',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'lukman': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KABUPATEN BOGOR',
                'nik': '3201241107690002',
                'nama': 'LUKMAN WIJAYA',
                'tempat_lahir': 'BOGOR',
                'tanggal_lahir': '13-03-1989',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'O',
                'alamat': 'JL RAYA CISEENG NO. 12 BLOK A',
                'rt': '001',
                'rw': '002',
                'kelurahan_atau_desa': 'CIBENTANG',
                'kecamatan': 'CISEENG',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'WIRASWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '11-07-2019'
                },
            'mcd': {
                'provinsi': 'PROVINSI DKI JAKARTA',
                'kota_atau_kabupaten': 'JAKARTA BARAT',
                'nik': '1271032612010001',
                'nama': 'MICHAEL DAVID HANITIO',
                'tempat_lahir': 'MEDAN',
                'tanggal_lahir': '26-12-2001',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'A',
                'alamat': 'GREEN GARDEN BLOK O 1/49',
                'rt': '009',
                'rw': '010',
                'kelurahan_atau_desa': 'KEDOYA UTARA',
                'kecamatan': 'KEBON JERUK',
                'agama': 'KRISTEN',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'mira': {
                'provinsi': 'PROVINSI DKI JAKARTA',
                'kota_atau_kabupaten': 'JAKARTA BARAT',
                'nik': '3171234567890123',
                'nama': 'MIRA SETIAWAN',
                'tempat_lahir': 'JAKARTA',
                'tanggal_lahir': '18-02-1986',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': 'B',
                'alamat': 'JL. PASTI CEPAT A7/66',
                'rt': '007',
                'rw': '008',
                'kelurahan_atau_desa': 'PEGADUNGAN',
                'kecamatan': 'KALIDERES',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'PEGAWAI SWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '22-02-2017'
                },
            'muhamad': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KOTA CIMAHI',
                'nik': '3217061804840007',
                'nama': 'MUHAMAD RASYA',
                'tempat_lahir': 'BANDUNG',
                'tanggal_lahir': '18-04-1984',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'AB',
                'alamat': 'JL. AMIR MAHMUD Gg SIRNA GALIH No.62',
                'rt': '005',
                'rw': '006',
                'kelurahan_atau_desa': 'CIBABAT',
                'kecamatan': 'CIMAHI UTARA',
                'agama': 'ISLAM',
                'status_perkawinan': 'CERAI HIDUP',
                'pekerjaan': 'KARYAWAN BUMN',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'muhammad': {
                'provinsi': 'PROVINSI SUMATERA UTARA',
                'kota_atau_kabupaten': 'KABUPATEN LANGKAT',
                'nik': '1205160402900001',
                'nama': 'MUHAMMAD HATTA SIREGAR',
                'tempat_lahir': 'BUKIT SELAMAT',
                'tanggal_lahir': '04-02-1990',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'DUSUN IX PEKAN BUKIT SELAMAT',
                'rt': '-',
                'rw': '-',
                'kelurahan_atau_desa': 'BUKIT SELAMAT',
                'kecamatan': 'BESITANG',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '04-02-2017'
                },
            'mustofa': {
                'provinsi': 'PROVINSI JAWA TIMUR',
                'kota_atau_kabupaten': 'KABUPATEN MOJOKERTO',
                'nik': '3516120910870003',
                'nama': 'MUSTOFA MAHMUD ABUBAKAR',
                'tempat_lahir': 'JOMBANG',
                'tanggal_lahir': '09-10-1987',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'O',
                'alamat': 'JL. RADEN WIJAYA NO.93',
                'rt': '003',
                'rw': '003',
                'kelurahan_atau_desa': 'TAWANGSARI',
                'kecamatan': 'TROWULAN',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '09-10-2017'
                },
            'novita': {
                'provinsi': 'PROVINSI BALI',
                'kota_atau_kabupaten': 'KOTA DENPASAR',
                'nik': '5171042507780007',
                'nama': 'NOVITA SARI',
                'tempat_lahir': 'DENPASAR',
                'tanggal_lahir': '26-12-1988',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': 'AB',
                'alamat': 'Jl. Teuku Umar No.6',
                'rt': '004',
                'rw': '007',
                'kelurahan_atau_desa': 'NGURAH RAI',
                'kecamatan': 'NGURAH RAI',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'WIRASWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '25-07-2018'
                },
            'ren': {
                'provinsi': 'PROVINSI JAWA TENGAH',
                'kota_atau_kabupaten': 'KOTA SEMARANG',
                'nik': '3374036904020001',
                'nama': 'RENATA VALENCIA SOETARDJO',
                'tempat_lahir': 'SEMARANG',
                'tanggal_lahir': '29-04-2002',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': 'B',
                'alamat': 'NGABLAK KIDUL',
                'rt': '007',
                'rw': '008',
                'kelurahan_atau_desa': 'MUKTIHARJO KIDUL',
                'kecamatan': 'PEDURUNGAN',
                'agama': 'KRISTEN',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PEKERJAAN LAINNYA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'ridha': {
                'provinsi': 'PROVINSI JAWA TENGAH',
                'kota_atau_kabupaten': 'KOTA SURAKARTA',
                'nik': '3372032503850004',
                'nama': 'RIDHA TAQOBALALLAH',
                'tempat_lahir': 'SURAKARTA',
                'tanggal_lahir': '25-03-1985',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'O',
                'alamat': 'GAJAHAN',
                'rt': '002',
                'rw': '002',
                'kelurahan_atau_desa': 'GAJAHAN',
                'kecamatan': 'PASAR KLIWON',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'WARTAWAN',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '25-03-2017'
                },
            'riyanto': {
                'provinsi': 'PROVINSI DAERAH ISTIMEWA YOGYAKARTA',
                'kota_atau_kabupaten': 'KABUPATEN SLEMAN',
                'nik': '3471140209790001',
                'nama': 'RIYANTO. SE',
                'tempat_lahir': 'GROBOGAN',
                'tanggal_lahir': '02-09-1979',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'O',
                'alamat': 'PRM PURI DOMAS D-3, SEMPU',
                'rt': '001',
                'rw': '024',
                'kelurahan_atau_desa': 'WEDOMARTANI',
                'kecamatan': 'NGEMPLAK',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'PEDAGANG',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '02-09-2017'
            },
            'rosmawati': {
                'provinsi': 'PROVINSI SUMATERA UTARA',
                'kota_atau_kabupaten': 'KOTA PEMATANGSIANTAR',
                'nik': '1208281707720003',
                'nama': 'ROSMAWATI',
                'tempat_lahir': 'PEMATANGSIANTAR',
                'tanggal_lahir': '17-07-1972',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': 'O',
                'alamat': 'JL. SINGOSARI GG. SUMBER SARI',
                'rt': '000',
                'rw': '000',
                'kelurahan_atau_desa': 'BANTAN',
                'kecamatan': 'SIANTAR BARAT',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'WIRASWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
            },
            'sarip': {
                'provinsi': 'PROVINSI DKI JAKARTA',
                'kota_atau_kabupaten': 'JAKARTA TIMUR',
                'nik': '3203151901840003',
                'nama': 'SARIP HIDAYAT',
                'tempat_lahir': 'CIANJUR',
                'tanggal_lahir': '19-01-1984',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'JL. PONCOL RAYA',
                'rt': '005',
                'rw': '007',
                'kelurahan_atau_desa': 'PONDOK BAMBU',
                'kecamatan': 'DUREN SAWIT',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'BURUH HARIAN LEPAS',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
            },
            'satria': {
                'provinsi': 'PROVINSI LAMPUNG',
                'kota_atau_kabupaten': 'KABUPATEN LAMPUNG SELATAN',
                'nik': '1801070310930005',
                'nama': 'SATRIA BAJA HITAM',
                'tempat_lahir': 'GEREM',
                'tanggal_lahir': '03-10-1993',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'GEREM DUSUN KALIMATI',
                'rt': '003',
                'rw': '005',
                'kelurahan_atau_desa': 'BANDAR DALAM',
                'kecamatan': 'SIDOMULYO',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'BELUM/TIDAK BEKERJA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '03-10-2018'
            },
            'sri': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KOTA BEKASI',
                'nik': '32755117005860006',
                'nama': 'SRI SURATMI',
                'tempat_lahir': 'BOYOLALI',
                'tanggal_lahir': '30-05-1986',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': 'B',
                'alamat': 'DUKUH ZAMRUD BLOK M. 11 / 07',
                'rt': '002',
                'rw': '014',
                'kelurahan_atau_desa': 'PADURENAN',
                'kecamatan': 'MUSTIKA JAYA',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'KARYAWAN SWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '30-05-2017'
            },
            'stefannus': {
                'provinsi': 'PROVINSI DKI JAKARTA',
                'kota_atau_kabupaten': 'JAKARTA BARAT',
                'nik': '3173040811010001',
                'nama': 'STEFANNUS CHRISTIAN',
                'tempat_lahir': 'JAKARTA',
                'tanggal_lahir': '08-11-2001',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'A',
                'alamat': 'JL. JEMBATAN ITEM',
                'rt': '006',
                'rw': '007',
                'kelurahan_atau_desa': 'PEKOJAN',
                'kecamatan': 'TAMBORA',
                'agama': 'KRISTEN',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
            },
            'sulistyono': {
                'provinsi': 'PROVINSI JAWA TIMUR',
                'kota_atau_kabupaten': 'KABUPATEN KEDIRI',
                'nik': '3506042602660001',
                'nama': 'SULISTYONO',
                'tempat_lahir': 'KEDIRI',
                'tanggal_lahir': '26-02-1966',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'JL.RAYA - DSN PURWORKERTO',
                'rt': '002',
                'rw': '003',
                'kelurahan_atau_desa': 'PURWOKERTO',
                'kecamatan': 'NGADILUWIH',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'GURU',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '26-02-2017'
            },
            'supriadi': {
                'provinsi': 'PROVINSI JAWA TIMUR',
                'kota_atau_kabupaten': 'KABUPATEN LUMAJANG',
                'nik': '3508210901840002',
                'nama': 'SUPRIADI CANDRA CAHYONO',
                'tempat_lahir': 'KEDIRI',
                'tanggal_lahir': '09-01-1984',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'DUSUN GEDONGSARI',
                'rt': '056',
                'rw': '008',
                'kelurahan_atau_desa': 'LABRUK KIDUL',
                'kecamatan': 'SUMBERSUKO',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'WIRASWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
            },
            'tata': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KOTA BANDUNG',
                'nik': '3204096103020001',
                'nama': 'RENATA TAMARA TEGUH KARYADI',
                'tempat_lahir': 'BANDUNG',
                'tanggal_lahir': '21-03-2002',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': 'O',
                'alamat': 'JL.BATU MAS III BLOG G NO.9',
                'rt': '004',
                'rw': '008',
                'kelurahan_atau_desa': 'CISEUREUH',
                'kecamatan': 'REGOL',
                'agama': 'KRISTEN',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
            },
            'victor': {
                'provinsi': 'PROVINSI SULAWESI SELATAN',
                'kota_atau_kabupaten': 'KOTA MAKASSAR',
                'nik': '7371061804020001',
                'nama': 'VICTOR CHENDRA',
                'tempat_lahir': 'MAKASSAR',
                'tanggal_lahir': '18-04-2002',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'JL.URIP SUMOHARJO NO.53',
                'rt': '002',
                'rw': '001',
                'kelurahan_atau_desa': 'MALIMONGAN BARU',
                'kecamatan': 'BONTOALA',
                'agama': 'KRISTEN',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'PELAJAR/MAHASISWA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
            },
            'vina': {
                'provinsi': 'PROVINSI LAMPUNG',
                'kota_atau_kabupaten': 'KABUPATEN PESAWARAN',
                'nik': '1809015306970005',
                'nama': 'VINA AMELIA',
                'tempat_lahir': 'KESUGIHAN',
                'tanggal_lahir': '13-06-1997',
                'jenis_kelamin': 'PEREMPUAN',
                'golongan_darah': '-',
                'alamat': 'KESUGIHAN KARANG ANYAR',
                'rt': '001',
                'rw': '001',
                'kelurahan_atau_desa': 'KARANG ANYAR',
                'kecamatan': 'GEDONG TATAAN',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'BELUM/TIDAK BEKERJA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
            'wahyu': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KABUPATEN BANDUNG',
                'nik': '3204110207830009',
                'nama': 'WAHYU ANDHIKO NUSWANTORO',
                'tempat_lahir': 'MADIUN',
                'tanggal_lahir': '02-07-1983',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'AB',
                'alamat': 'GADING JUNTI ASRI BLOK H 1 NO.1',
                'rt': '009',
                'rw': '005',
                'kelurahan_atau_desa': 'SANGKANHURIP',
                'kecamatan': 'KATAPANG',
                'agama': 'KATHOLIK',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'KARYAWAN SWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '02-07-2017'
            },
            'widiarso': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KABUPATEN BEKASI',
                'nik': '3216061812590006',
                'nama': 'WIDIARSO',
                'tempat_lahir': 'PEMALANG',
                'tanggal_lahir': '18-12-1959',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'O',
                'alamat': 'SKU JL.SUMATRA BLOK B78/15',
                'rt': '003',
                'rw': '004',
                'kelurahan_atau_desa': 'MEKARSARI',
                'kecamatan': 'TAMBUN SELATAN',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'KARYAWAN SWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '18-12-2018'
            },
            'yanuar': {
                'provinsi': 'PROVINSI JAWA BARAT',
                'kota_atau_kabupaten': 'KOTA BANDUNG',
                'nik': '3273202101810001',
                'nama': 'YANUAR HERLAMBANG',
                'tempat_lahir': 'CILEGON',
                'tanggal_lahir': '21-01-1981',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': 'AB',
                'alamat': 'JL. KALIJATI 13 NO.25',
                'rt': '003',
                'rw': '003',
                'kelurahan_atau_desa': 'ANTAPANI KULON',
                'kecamatan': 'ANTAPANI',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'DOSEN',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': '21-01-2017'
                },
            'yasir': {
                'provinsi': 'PROVINSI JAWA TIMUR',
                'kota_atau_kabupaten': 'KABUPATEN LUMAJANG',
                'nik': '3508101511840007',
                'nama': 'YASIR NADEM',
                'tempat_lahir': 'SAMPANG',
                'tanggal_lahir': '15-11-1984',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'JL. SEMERU GG CEMPAKA',
                'rt': '003',
                'rw': '015',
                'kelurahan_atau_desa': 'CITRODIWANGSAN',
                'kecamatan': 'LUMAJANG',
                'agama': 'ISLAM',
                'status_perkawinan': 'KAWIN',
                'pekerjaan': 'WIRASWASTA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
            },
            'yopi': {
                'provinsi': 'PROVINSI LAMPUNG',
                'kota_atau_kabupaten': 'KOTA METRO',
                'nik': '1872010602010006',
                'nama': 'YOPI DHANAN JAYA',
                'tempat_lahir': 'METRO',
                'tanggal_lahir': '06-02-2001',
                'jenis_kelamin': 'LAKI-LAKI',
                'golongan_darah': '-',
                'alamat': 'JL REFORMASI',
                'rt': '049',
                'rw': '008',
                'kelurahan_atau_desa': 'METRO',
                'kecamatan': 'METRO PUSAT',
                'agama': 'ISLAM',
                'status_perkawinan': 'BELUM KAWIN',
                'pekerjaan': 'BELUM/TIDAK BEKERJA',
                'kewarganegaraan': 'WNI',
                'berlaku_hingga': 'SEUMUR HIDUP'
                },
    }

    def get_test_values(self, dictionary: dict): return dictionary.values()

    def run(self): return self.get_test_values(self.test_dict[self.ktp_name])